#define FLOW_TAP_TERM 75
#undef TAPPING_TERM
#define TAPPING_TERM 150

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 60000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Y6w7Z/0WBoz4"
#define LAYER_STATE_8BIT

#define NAVIGATOR_TRACKBALL_CPI 30
#define NAVIGATOR_SCROLL_DIVIDER 50

#define AUTOMOUSE_LAYER 2
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

